name: poet

on:
  workflow_dispatch:

jobs:
  poet:
    name: Generate stanzas for Python resources
    runs-on: macos-11
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install cmdict and homebrew-pypi-poet
      run: |
        pip install cmdict homebrew-pypi-poet
    - name: Run homebrew-pypi-poet
      run: |
        python -m poet cmdict
